# Generated by Django 3.2.17 on 2023-02-05 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dashboard', '0002_auto_20230205_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 5, 24, 664514)),
        ),
    ]
